// ========================================
// Imports
// ========================================
import { Suspense } from "react";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

// components
import { Providers } from "@/components/providers/providers";
import { NavigationProgress } from "@/components/navigation-progress";
import { Toaster } from "sonner";

// ========================================
// Font family
// ========================================
const fontFamily = Mulish({
  subsets: ["latin"],
  display: "swap",
});

// ========================================
// Metadata
// ========================================
export const metadata: Metadata = {
  title: "Careerly Tanstack",
  description: "Generated by create next app",
};

// ========================================
// Root layout
// ========================================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontFamily.className}  antialiased`}>
        <Suspense>
          <NavigationProgress />
        </Suspense>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
